use_frameworks!

platform :ios, '9.0'

target 'images_Example' do
  pod 'images', :path => '../'

  target 'images_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
